# Generated by Django 2.2.18 on 2021-02-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lastWord', models.CharField(max_length=50)),
            ],
        ),
    ]
