# Generated by Django 2.2.18 on 2021-02-19 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siritori', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='key',
            new_name='userID',
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='siritori.Session')),
            ],
        ),
    ]
