# Generated by Django 2.2.18 on 2021-02-21 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siritori', '0003_auto_20210220_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='dateAdded',
        ),
        migrations.AddField(
            model_name='link',
            name='whenCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
